{% set name = "oslo.config" %}
{% set version = "9.1.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "85342c1c4ba658781673f57da0260c4831045353cad2df325fd374e1783d2a6b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - pbr >=2.0.0

  run:
    - python >=3.8
    - debtcollector >=1.2.0
    - netaddr >=0.7.18
    - stevedore >=1.20.0
    - oslo.i18n >=3.15.3
    - rfc3986 >=1.2.0
    - pyyaml >=5.1
    - requests >=2.18.0

test:
  imports:
    - oslo_config
    - oslo_config.cfg
    - oslo_config.types
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://docs.openstack.org/developer/oslo.config/
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: The Oslo configuration API supports parsing command line arguments and .ini style configuration files.
  doc_url: http://docs.openstack.org/developer/oslo.config/
  dev_url: http://git.openstack.org/cgit/openstack/oslo.config

extra:
  recipe-maintainers:
    - anguslees
    - tschoonj
