{%set name = "oslo.config" %}
{%set version = "4.1.0" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash = "06ef517c3339ee13da0d252012baa7448da08fca2495c243b10696f146ae71c6" %}
{%set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pbr >=2.0.0

  run:
    - python
    - debtcollector >=1.2.0
    - netaddr !=0.7.16,>=0.7.13
    - six >=1.9.0
    - stevedore >=1.20.0
    - oslo.i18n >=2.1.0
    - rfc3986 >=0.3.1

test:
  imports:
    - oslo_config
    - oslo_config.cfg
    - oslo_config.types

about:
  home: http://docs.openstack.org/developer/oslo.config/
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: 'The Oslo configuration API supports parsing command line arguments and .ini style configuration files.'
  doc_url: http://docs.openstack.org/developer/oslo.config/
  dev_url: http://git.openstack.org/cgit/openstack/oslo.config

extra:
  recipe-maintainers:
    - pmlandwehr
    - anguslees
