{% set name = "oslo.config" %}
{% set version = "6.10.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "98427e4a4c1d0530ed2954c3efe610fa8de377f4dfeabe7eb951d02508797408" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - pbr >=2.0.0

  run:
    - python
    - debtcollector >=1.2.0
    - netaddr >=0.7.18
    - six >=1.10.0
    - stevedore >=1.20.0
    - oslo.i18n >=3.15.3
    - rfc3986 >=0.3.1
    - pyyaml >=3.12
    - enum34 >=1.0.4  # [py2k]
    - requests >=2.18.0

test:
  imports:
    - oslo_config
    - oslo_config.cfg
    - oslo_config.types

about:
  home: http://docs.openstack.org/developer/oslo.config/
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: 'The Oslo configuration API supports parsing command line arguments and .ini style configuration files.'
  doc_url: http://docs.openstack.org/developer/oslo.config/
  dev_url: http://git.openstack.org/cgit/openstack/oslo.config

extra:
  recipe-maintainers:
    - pmlandwehr
    - anguslees
