appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: BHCXK8s8JGBJbiHcqOYbsnYVIRD3kwWCeR3JChgr23Nvi9bS5H/2rkhdpwBAzQsoVe+WqgLhcYH+0xPkFSD0UKWwhxFCBaXG0kTPP1UJSzJtYeLFJ081uwnTCeIzrBYAfu5P8LESwXajh0GwWi1uTlzfXO1q0fh7cbNx7K2FFIwB89ychGirfDG4sSDu057+f5qumUgpyI/wD9Sv4Zi4cJGMVYEDyHKWLTC98wN46YLKVGHL+PTIE9BP+mhKwOjqLrPjR/ZweLEx1tdlF4xEvaYfsnQrhHB/zoeeJJCc0zTbqYpxTdUIJREk2eIyZJPtxFkA8lfFNZB7WUA3bcqbnH4pM0M7/5AT1UJEPLXf3r9J1zgdD829D2R7sUHoYaB8sHdFR6IJdPmvSvEXuMPHqgIDxmRY0ZnKZb9YL0assD4/AvkC183DvY4DkmYtyROudZWLDHMBvBUorwGVrqQ8EBUeB4XngmnBg+59U0222mnzAsRsHPIjm9A8G/4uFoYcb2H6pzdXBxqXHhE3ZUpXoJHMr8Z7VH7DxqMu1VT/U4AwMOzFVmyYfcUfjwm83lStKekHTNHi4tok0r5/VdG4LOh/gDKjhsWC07pzRTQS5MwhMCw0sGfSuEoza4zBky06JAMW7u0jCf2IQAlW4FpPt7V82NXxok/dDyEb65CMWyo=}
provider:
  win: azure
conda_forge_output_validation: true
